### PR TITLE
Remove componentWillMount

### PR DESCRIPTION
**Pull request by nghiepdev**
Hide the deprecation warning React >= 16.9

### CODE REVIEW

**Comment by borgstrom** [comment]
cc @malte-wessel

**Comment by bogdancss** [comment]
will this get merged?

**Review by alekmieczkowski — APPROVED** [review]

**Comment by shyce** [comment]
is this library dead? last update was 2 years ago and @malte-wessel seems to be working on other libs

**Comment by alflennik** [comment]
When I saw the warning I had a feeling I would find an open PR like this 🥺

**Comment by JoshuaAYoung** [comment]
Using text-fit for a new project. Was so much easier than fitty, but might need to switch over since we're fast approaching deprecation.

**Comment by gtk-hs** [comment]
Can we get this merged in? This library seems to work fine, it's a shame that a two line change is going to keep people from using this...

**Review by lucascepeda — APPROVED** [review]

**Review by jakeonfire — APPROVED** [review]

**Comment by jakeonfire** [comment]
@malte-wessel could you please dedicate a few minutes for your hundreds of users of this project? or give someone else write access? 🙏 🙏 🙏

**Comment by jakeonfire** [comment]
cc @denis-sokolov @ValBerthe @chrisdrackett @umidbekkarimov @tbroadley

**Comment by jakeonfire** [comment]
thank you @denis-sokolov! sorry for the spam.

**Pull request merged**
